### ISSUE TITLE
Add option to join multiple tables at once

### ISSUE THREAD

**Issue by raumregionmensch** [raumregionmensch/rrm-plugin#11]
Perhaps we should add a 'Trigger wizard' to join multiple tables at once by selecting a source and a target schema.

![trigger_wizard_1](https://user-images.githubusercontent.com/22611509/28306924-743ca5a4-6ba1-11e7-9758-08c0542e8d82.png)

![trigger_wizard_2](https://user-images.githubusercontent.com/22611509/28306939-7e9b6814-6ba1-11e7-91f5-feb8fc3fb0ae.png)

* Source schema
-> Schema that contains the source geometries
* Target schema
-> Schema that contains the target geometries ("sample points")

* Table
-> Option 1: Join tables that share the same name (source schema must differ from target schema)
-> Option 2: Use prefix for target tables
-> Option 3: Use suffix for target tables
-> Option 4: Use prefix for source tables
-> Option 5: Use suffix for source tables

* Fields
-> Option 1: Sample fields that share the same name
-> Option 2: Use prefix for target fields
-> Option 3: Use suffix for target fields
-> Option 4: Use prefix for source fields
-> Option 5: Use suffix for source fields

If the source tables are named "table_a", "table_b", "table_c" and the target tables are named "label_table_a", "label_table_b", "label_table_c" the option "Use prefix for target tables" (label_) could be used to join all tables at once. The geometry field shouldn't be sampled.

**Comment by sklencar** [comment]
Can you give some more info about "Do not sample UIC" feature? What does UIC stands for and what the checkbox suppose to be for?

**Comment by raumregionmensch** [comment]
If the UIC of the source table shares the same name as the UIC of the target table (e.g. 'gid'), the UIC should not be sampled (for 'Sample fields that share the same name').

**Comment by sklencar** [comment]
Similarly as it is in single trigger settings, a checkbox goes with each field pair to indicate whether it will be sampled or not. However, a bit more of user interaction is needed. Does it covered the user case?

**Comment by raumregionmensch** [comment]
Let's say 'table_a' (source table) contains the fiels 'gid', 'geom', 'att_1', 'att_2, 'att_3', 'att_4', 'att_5' and 'label_table_a' (target table) also contains the fields 'gid', 'geom', 'att_1', 'att_2, 'att_3', 'att_4', 'att_5', 'label_rotation'. The option 'Sample fields that share the same name' should join the fields automatically (except gid/geom):
 
[soruce table -> target table]
att_1 -> att_1
att_2 -> att_2
att_3 -> att_3
att_4 -> att_4
att_5 -> att_5

This way a lot of tables (table_a -> label_table_a; table_b -> label_table_b; ...) can be joined with just a few clicks.

**Comment by sklencar** [comment]
Right, it joins fields automatically according selected option and input for that option. In addition, user can also disable sampling for other fields pairs beside UIC field and geom manually by using checkboxes for each fields pair.

**Comment by raumregionmensch** [comment]
For us, there is no need to disable other matching field pairs than UIC an geometry. In many cases schemas will contain dozens of tables. Listening all fields might be confusing.

**Comment by sklencar** [comment]
Sure, this option will be disabled and only matching tables with at least one matching field pair will be shown.

**Comment by wonder-sk** [comment]
Implemented in #15
