### ISSUE TITLE
Trigger wizard should not duplicate existing triggers

### ISSUE THREAD

**Issue by raumregionmensch** [raumregionmensch/rrm-plugin#22]
The trigger wizard ignores existing triggers. So it's possible to duplicate triggers  (same source table, same target table, same fields joined) when running the wizard. To me, it would be better not to create triggers that already exist.

**Comment by raumregionmensch** [comment]
Is there any need that triggers that join the same tables exist simultaneously? Perhaps the trigger wizard should overwrite these triggers without checking the relationship of the fields.

**Comment by sklencar** [comment]
I agree that triggers that join the same tables should be not permitted for more transparent workflow. To add/delete/modified joined fields for a certain trigger, the trigger configuration tool can be simply used to changed it.

Would be enough to notify a user when attempts to create already existing trigger again?

**Comment by raumregionmensch** [comment]
To me, a popup dialog should do the job:

'... triggers already exists.'
-> Replace existing triggers/Cancel

**Comment by raumregionmensch** [comment]
Fixed in QGIS 2.x but not in QGIS 3.x.
