### ISSUE TITLE
Plugin broken if table is deleted before deleting triggers

### ISSUE THREAD

**Issue by raumregionmensch** [raumregionmensch/rrm-plugin#7]
If a table is deleted before deleting all existing triggers, it's no longer possible to access the plugin. There should a be an auto-repair function to delete the broken triggers completely.

![delete_table_1](https://cloud.githubusercontent.com/assets/22611509/24263740/58bbc606-0ffe-11e7-82f9-234da2b308e4.png)
![delete_table_2](https://cloud.githubusercontent.com/assets/22611509/24263748/5f2e82da-0ffe-11e7-8730-74e5dd464dea.png)

**Comment by wonder-sk** [comment]
Fixed in pull request #14
