### ISSUE TITLE
Triggers broken after renaming schema

### ISSUE THREAD

**Issue by raumregionmensch** [raumregionmensch/rrm-plugin#8]
After renaming a schema, existing triggers are no longer working. Is there a way to fix this?

**Comment by sklencar** [comment]
@raumregionmensch Its a bit more complicated to detect and fix broken triggers after renaming schema which requires some extra time beside scheduled time. If such case happens rarely I would suggest to delete all related triggers and configure them again. However, if you confirm that its crucial issue, it can be sort it out.

**Comment by raumregionmensch** [comment]
At the moment, an option to delete all related triggers should do the job.

**Comment by raumregionmensch** [comment]
![invalid_trigger](https://user-images.githubusercontent.com/22611509/35722707-a72076d8-07f7-11e8-932b-7e9cae96538b.jpg)

Many thx, but the dialog should list the name of the affected database(s)/schema(s). This information is quite important to fix the broken triggers manually.

**Comment by sklencar** [comment]
Invalid triggers are highlighted on the list of all triggers in config window afterwards if are not deleted.
